apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: ahmedelselly/posts:0.0.2
          # ports:
          #   - containerPort: 4000
          # env:
          #   - name: POSTS_SERVICE_HOST
          #     value: posts
          #   - name: POSTS_SERVICE_PORT
          #     value: "4000"
